# -*- coding: utf-8 -*-
RABBITMQ_HOST = '127.0.0.1'
RABBITMQ_PORT = '5672'
RABBITMQ_USER_NAME = 'guest'
RABBITMQ_USER_PASSWORD = 'guest'

RABBITMQ_ALEPH_VIRTUALHOST = "aleph"
RABBITMQ_ALEPH_INPUT_QUEUE = "aleph-search"
RABBITMQ_ALEPH_OUTPUT_QUEUE = "aleph-search"
RABBITMQ_ALEPH_INPUT_KEY = "search.request"
RABBITMQ_ALEPH_OUTPUT_KEY = "search.response"
